> jars <- c("commons-math3-3.2.jar","shallot.jar")
> source("common.R",print.eval=TRUE)
# R version 3.4.2 (2017-09-28) # hilton # FALSE # TRUE
> 
> tryCatch(s %~% 'new org.apache.commons.math3.random.EmpiricalDistribution()',error=function(e) e)   # Scala 2.11.x class loader is weird.  This line avoid subsequent problems.
ScalaInterpreterReference... res1: org.apache.commons.math3.random.EmpiricalDistribution
> 
> 
> rscala:::scalap(s,"org.apache.commons.math3.random.RandomDataGenerator")
package org.apache.commons.math3.random;
class RandomDataGenerator extends scala.AnyRef with java.io.Serializable with org.apache.commons.math3.random.RandomData {
  final var secRand: java.security.SecureRandom;
  final var rand: org.apache.commons.math3.random.RandomGenerator;
  def getNatural(scala.Int): scala.Array[scala.Int];
  def shuffle(scala.Array[scala.Int], scala.Int): scala.Unit;
  def getSecRan(): java.security.SecureRandom;
  def initRan(): scala.Unit;
  def getRandomGenerator(): org.apache.commons.math3.random.RandomGenerator;
  def setSecureAlgorithm(java.lang.String, java.lang.String): scala.Unit;
    throws java.security.NoSuchAlgorithmException, java.security.NoSuchProviderException
  def reSeed(): scala.Unit;
  def reSeedSecure(scala.Long): scala.Unit;
  def reSeedSecure(): scala.Unit;
  def reSeed(scala.Long): scala.Unit;
  def nextSample(java.util.Collection, scala.Int): scala.Array[scala.Any];
    throws org.apache.commons.math3.exception.NumberIsTooLargeException, org.apache.commons.math3.exception.NotStrictlyPositiveException
  def nextPermutation(scala.Int, scala.Int): scala.Array[scala.Int];
    throws org.apache.commons.math3.exception.NumberIsTooLargeException, org.apache.commons.math3.exception.NotStrictlyPositiveException
  def nextUniform(scala.Double, scala.Double, scala.Boolean): scala.Double;
    throws org.apache.commons.math3.exception.NumberIsTooLargeException, org.apache.commons.math3.exception.NotFiniteNumberException, org.apache.commons.math3.exception.NotANumberException
  def nextUniform(scala.Double, scala.Double): scala.Double;
    throws org.apache.commons.math3.exception.NumberIsTooLargeException, org.apache.commons.math3.exception.NotFiniteNumberException, org.apache.commons.math3.exception.NotANumberException
  def nextF(scala.Double, scala.Double): scala.Double;
    throws org.apache.commons.math3.exception.NotStrictlyPositiveException
  def nextChiSquare(scala.Double): scala.Double;
  def nextCauchy(scala.Double, scala.Double): scala.Double;
  def nextBinomial(scala.Int, scala.Double): scala.Int;
  def nextBeta(scala.Double, scala.Double): scala.Double;
  def nextZipf(scala.Int, scala.Double): scala.Int;
    throws org.apache.commons.math3.exception.NotStrictlyPositiveException
  def nextWeibull(scala.Double, scala.Double): scala.Double;
    throws org.apache.commons.math3.exception.NotStrictlyPositiveException
  def nextT(scala.Double): scala.Double;
    throws org.apache.commons.math3.exception.NotStrictlyPositiveException
  def nextPascal(scala.Int, scala.Double): scala.Int;
    throws org.apache.commons.math3.exception.NotStrictlyPositiveException, org.apache.commons.math3.exception.OutOfRangeException
  def nextHypergeometric(scala.Int, scala.Int, scala.Int): scala.Int;
    throws org.apache.commons.math3.exception.NotPositiveException, org.apache.commons.math3.exception.NotStrictlyPositiveException, org.apache.commons.math3.exception.NumberIsTooLargeException
  def nextGamma(scala.Double, scala.Double): scala.Double;
    throws org.apache.commons.math3.exception.NotStrictlyPositiveException
  def nextExponential(scala.Double): scala.Double;
    throws org.apache.commons.math3.exception.NotStrictlyPositiveException
  def nextGaussian(scala.Double, scala.Double): scala.Double;
    throws org.apache.commons.math3.exception.NotStrictlyPositiveException
  def nextPoisson(scala.Double): scala.Long;
    throws org.apache.commons.math3.exception.NotStrictlyPositiveException
  def nextSecureLong(scala.Long, scala.Long): scala.Long;
    throws org.apache.commons.math3.exception.NumberIsTooLargeException
  def nextSecureInt(scala.Int, scala.Int): scala.Int;
    throws org.apache.commons.math3.exception.NumberIsTooLargeException
  def nextSecureHexString(scala.Int): java.lang.String;
    throws org.apache.commons.math3.exception.NotStrictlyPositiveException
  def nextLong(scala.Long, scala.Long): scala.Long;
    throws org.apache.commons.math3.exception.NumberIsTooLargeException
  def nextInt(scala.Int, scala.Int): scala.Int;
    throws org.apache.commons.math3.exception.NumberIsTooLargeException
  def nextHexString(scala.Int): java.lang.String;
    throws org.apache.commons.math3.exception.NotStrictlyPositiveException
  def this(org.apache.commons.math3.random.RandomGenerator): scala.Unit;
  def this(): scala.Unit;
}
object RandomDataGenerator {
  def nextLong(org.apache.commons.math3.random.RandomGenerator, scala.Long): scala.Long;
    throws java.lang.IllegalArgumentException
  def nextLong(java.security.SecureRandom, scala.Long): scala.Long;
    throws java.lang.IllegalArgumentException
  final val serialVersionUID: scala.Long;
}
> s$.org.apache.commons.math3.random.RandomDataGenerator
ScalaInterpreterItem for org.apache.commons.math3.random.RandomDataGenerator
> rdg <- s$.org.apache.commons.math3.random.RandomDataGenerator$new()
> 
> rdg$reSeed(39234L)
> rexp <- rdg$nextExponential(2,.EVALUATE=FALSE)
> 
> library(microbenchmark)
> options(width=120)
> microbenchmark(rdg$nextExponential(4),rexp(4),times=1000L)
Unit: microseconds
                   expr     min        lq     mean    median        uq      max neval
 rdg$nextExponential(4) 600.322 1100.1935 1719.402 1335.6880 1539.8820 30856.43  1000
                rexp(4) 390.275  662.9895 1101.449  826.8135  929.7255 39093.02  1000
> microbenchmark(rdg$nextExponential(4),rexp(4),times=1000L)
Unit: microseconds
                   expr     min        lq      mean   median        uq      max neval
 rdg$nextExponential(4) 585.667 1025.7990 1549.1178 1224.658 1382.5525 48646.46  1000
                rexp(4) 380.482  660.9295  989.9868  772.414  859.5485 30767.60  1000
> microbenchmark(rdg$nextExponential(4),rexp(4),times=1000L)
Unit: microseconds
                   expr     min       lq     mean   median       uq      max neval
 rdg$nextExponential(4) 525.512 682.2165 1134.880 992.7195 1138.474 94379.81  1000
                rexp(4) 341.064 428.9910  699.628 614.2135  745.086 23629.47  1000
> 
> s$.org.ddahl.shallot.parameter.Mass
ScalaInterpreterItem for org.ddahl.shallot.parameter.Mass
> massFactory3 <- s$.org.ddahl.shallot.parameter.Mass$factory(1.0,3.0,rdg)
> s %~% "3+4"
[1] 7
> 
> mass <- s$.org.ddahl.shallot.parameter.Mass$apply(3.4)
> massFactory1 <- s$.org.ddahl.shallot.parameter.Mass$factory(mass)
> massFactory2 <- s$.org.ddahl.shallot.parameter.Mass$factory(3.0)
> massFactory3 <- s$.org.ddahl.shallot.parameter.Mass$factory(1.0,3.0,rdg)
> massFactory3$apply()$logValue()
[1] -2.27295
> massFactory3$apply()$logValue()
[1] -3.893189
> massFactory3$apply()$logValue()
[1] -2.183371
> 
> 
> 
> s %@% '
+ class Bob {
+ 
+   val a = 3.0
+   var b = 4.0
+ 
+   def sum(c: Int) = { a + b + c }
+ 
+ }
+ '
> 
> d <- s$.Bob$new()
> d[['type']]                           # Note the weird 'iw$' prepended to 'Bob'
[1] "iw$Bob"
> tryCatch(d$b(),error=function(e) e)   # Doesn't work
<console>:15: error: not found: type iw$Bob
       R.cached(".9").asInstanceOf[iw$Bob].b
                                   ^
<simpleError in d$b(): Problem defining function.>
> 
> d[['type']] <- "Bob"     # Cast it to be 'Bob'
> d$b()                    # Now it does
[1] 4
> 
> d$sum(4L)
[1] 11
> m <- d$sum(5L,.EVALUATE=FALSE)
> 
> m(3)                                                   # Casting is not necessary here
[1] 10
> d$sum(as.integer(3))                                   # But it is here
[1] 10
> 
> 
